parameters:
    admin_password:    change_this
    database_host:     db
    database_port:     5432
    database_name:     postgres
    database_user:     postgres
    database_password: postgres

    locale:            fr
    secret:            IamnotSoSecret

    debug_toolbar:          true
    debug_redirects:        false
    use_assetic_controller: true
